CREATE DATABASE Dojo

USE Dojo

CREATE TABLE Tarefa (
    IdTarefa UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Titulo VARCHAR(255) NOT NULL,
    Descricao VARCHAR(MAX) NULL,
    Status VARCHAR(50) NOT NULL,
    DataCriacao DATETIME NOT NULL DEFAULT GETDATE()
);

SELECT * FROM Tarefa;